### ISSUE TITLE
Avoid ros-humble-octomap clobbering octomap

### ISSUE THREAD

**Issue by Tobias-Fischer** [RoboStack/ros-humble#10]

**Comment by Tobias-Fischer** [comment]
How about doing sth like this: https://github.com/RoboStack/ros-galactic/blob/main/additional_recipes/ros-galactic-cartographer/recipe.yaml @wolfv?

**Comment by traversaro** [comment]
Those repos shadow the upstream ones? In that case, that would be great. Cross-link to https://github.com/RoboStack/ros-noetic/issues/20 .

**Comment by Tobias-Fischer** [comment]
Yeah - the issue is that they need manual updating and rebuilding when new versions come out.

**Comment by traversaro** [comment]
This is kind of related to https://github.com/ros/rosdistro/issues/26527, even if that issue was just for Noetic.

**Comment by Tobias-Fischer** [comment]
Fixed with #21 - not sure which other packages are vendored in ROS2

**Comment by traversaro** [comment]
> Fixed with #21 - not sure which other packages are vendored in ROS2

Many of them, some of them are tracked in https://github.com/RoboStack/ros-noetic/issues/20, but probably we could keep a ROS2-specific issue. Anyhow, I am not sure if we want to fix all of them now, it may be non-trivial to do so.

**Comment by Tobias-Fischer** [comment]
Fixed with the new builds :)
