### ISSUE TITLE
Package request: ros-gz-humble-ros

### ISSUE THREAD

**Issue by sebbyjp** [RoboStack/ros-humble#111]
### Package name

ros_gz

### Operating System(s)

- [ ] linux-64
- [ ] linux-aarch64
- [ ] osx-64
- [X] osx-arm64
- [ ] win-64

### Additional context (optional)

I believe the correct way to install the package is: `conda install ros-humble-ros-gz` but it cannot be found.

**Comment by Tobias-Fischer** [comment]
Duplicated: #68
