### ISSUE TITLE
Package request: ros-humble-rosidl-generator-dds-idl

### ISSUE THREAD

**Issue by jc-bao** [RoboStack/ros-humble#125]
### Package name

ros-humble-rosidl-generator-dds-idl

### Operating System(s)

- [X] linux-64
- [ ] linux-aarch64
- [ ] osx-64
- [ ] osx-arm64
- [ ] win-64

### Additional context (optional)

I am currently working with a package that is crucial for ROS communication. The package is supported both in `Foxy` and `Galactic` conda environment. However, I've noticed that this package appears to be absent in the `Humble` distribution.

As I am fairly new to RoboStack, I am curious to understand the reasoning behind this missing package within the `Humble` distribution. Moreover, I would appreciate any guidance on possible workarounds or alternatives that could be used when particular packages are unavailable within a given distribution.

**Comment by Tobias-Fischer** [comment]
Has been added :)
