### ISSUE TITLE
Package request: ros-humble-control-toolbox v3.2.0

### ISSUE THREAD

**Issue by bjin-bdai** [RoboStack/ros-humble#161]
### Package name

ros-humble-control-toolbox v3.2.0

### Operating System(s)

- [X] linux-64
- [ ] linux-aarch64
- [ ] osx-64
- [ ] osx-arm64
- [ ] win-64

### Additional context (optional)

[Documentation](https://robostack.github.io/humble.html) states that v3.2.0 is available, but a `mamba search ros-humble-control-toolbox` yields the following:

```
Loading channels: done                                                      
# Name                       Version           Build  Channel               
ros-humble-control-toolbox           2.0.2  py39h6fdeb60_0  robostack-humble
ros-humble-control-toolbox           2.1.0  py39h63710d1_1  robostack-humble
ros-humble-control-toolbox           2.1.0  py39h6fdeb60_0  robostack-humble
```

**Comment by Tobias-Fischer** [comment]
Looks like you’re using the wrong channel - please use robostack-staging

**Comment by Tobias-Fischer** [comment]
https://anaconda.org/robostack-staging/ros-humble-control-toolbox
