### ISSUE TITLE
Package request: ros-humble-moveit-planners-chomp

### ISSUE THREAD

**Issue by MannavaVivek** [RoboStack/ros-humble#183]
### Package name

ros-humble-moveit-planners-chomp

### Operating System(s)

- [X] linux-64
- [X] linux-aarch64
- [X] osx-64
- [X] osx-arm64
- [X] win-64

### Additional context (optional)

The CHOMP motion planner for MoveIt2

### Links and references (optional)

https://github.com/moveit/moveit2/tree/humble/moveit_planners/chomp

**Comment by Tobias-Fischer** [comment]
If you open a pull request adding this package we’ll be happy to accept it if the packages build

**Comment by Tobias-Fischer** [comment]
Done in #190
