### ISSUE TITLE
Package request: ros2_control

### ISSUE THREAD

**Issue by AshrithSagar** [RoboStack/ros-humble#213]
### Package name

ros2_control

### Operating System(s)

- [X] linux-64
- [X] linux-aarch64
- [X] osx-64
- [X] osx-arm64
- [X] win-64

### Links and references (optional)

https://github.com/ros-controls/ros2_control

**Comment by Tobias-Fischer** [comment]
Available on all platforms already, closing: https://anaconda.org/robostack-staging/ros-humble-ros2-control
