### ISSUE TITLE
Package request: Navigation2 1.1.17

### ISSUE THREAD

**Issue by mini-1235** [RoboStack/ros-humble#232]
### Package name

Navigation2 1.1.17

### Operating System(s)

- [X] linux-64
- [ ] linux-aarch64
- [ ] osx-64
- [ ] osx-arm64
- [ ] win-64

### Additional context (optional)

Navigation2 has a minor update on humble https://github.com/ros-navigation/navigation2/releases/tag/1.1.17, I noticed that the version on robostack is still 1.1.13, is it possible to have a latest version on it?

**Comment by Tobias-Fischer** [comment]
Will be fixed once #229 is merged

**Comment by mini-1235** [comment]
thanks
