### ISSUE TITLE
ROS2 AARCH64 needs rebuild

### ISSUE THREAD

**Issue by b1n-ch1kn** [RoboStack/ros-humble#34]
Reference query: https://gitter.im/RoboStack/Lobby?at=6379895a2cb657024035f2ab

Host: Jetson Nano, robostack-humble
Mamba Packages: https://pastebin.com/raw/ww0ax7Zr

When building custom msgs on Humble (and Python 3.9), we run into the following error: https://pastebin.com/raw/yA9JraPd.
Specifically:
```
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
```

"rosidl_generator_c-extras.cmake contains the wrong `site-packages` path, with python3.1 instead of python3.10"

@Tobias-Fischer believes there's a CI setup issue on aarch64.

**Comment by Tobias-Fischer** [comment]
Yes - we need to rebuild the packages but the CI times out after 20 minutes @wolfv

**Comment by Tobias-Fischer** [comment]
Hi @aktech, sorry to ping you. Our cirun builds time out after 25 minutes. Is this normal?

**Comment by aktech** [comment]
Hey @Tobias-Fischer that's not normal, I'll take a look. Can you share the build please? (also, don't hesitate to ping me)

**Comment by aktech** [comment]
I guess you're referring these:

<img width="293" alt="Screenshot 2023-01-24 at 8 12 47 am" src="https://user-images.githubusercontent.com/5647941/214241687-75190367-be81-4fb1-b5a6-537cb761790c.png">

Looking at the summary, it seems they were potentially starving of memory/cpu, try a larger instance maybe?
<img width="1560" alt="Screenshot 2023-01-24 at 8 13 24 am" src="https://user-images.githubusercontent.com/5647941/214241744-de785b88-7ec8-46b3-9bd7-e5eb26abca5d.png">


I checked our database and saw they were terminated after instructed github's webhook, so un natural termination by cirun:

| name                                | terminated_at              | terminated_via |
| ----------------------------------- | -------------------------- | -------------- |
| cirun-robostack--ros-humble-c60ab63 | 2023-01-24 06:31:43.668931 | webhook        |
| cirun-robostack--ros-humble-e62946f | 2023-01-24 06:36:44.147264 | webhook        |

**Comment by Tobias-Fischer** [comment]
@wolfv  any chance you could setup a larger server to test?

**Comment by wolfv** [comment]
@Tobias-Fischer we can use xxlarge: https://github.com/RoboStack/ros-humble/blob/540c44e42d3fe63a7b5a8cc45c46aa3719227cb9/.cirun.yml#L4

**Comment by wolfv** [comment]
Sorry, it's 2xlarge (or larger :)

<img width="848" alt="Screenshot 2023-01-24 at 11 12 14" src="https://user-images.githubusercontent.com/885054/214265132-cf297687-20bc-423c-90a8-2689e80710c9.png">

**Comment by aktech** [comment]
Let me know if it doesn't works with that too, we can debug together.

**Comment by Tobias-Fischer** [comment]
Seems to have worked. Thanks everyone!
