### ISSUE TITLE
Add ros-humble-turtlebot3 and ros-humble-turtlebot3-gazebo to more target platforms

### ISSUE THREAD

**Issue by nikolausWest** [RoboStack/ros-humble#53]
First off, thanks for actually making it feasible to use ROS on a Mac! Really great job!

Gazebo and turtlebot3 are commonly used for introduction tutorials with ROS. We're putting together a tutorial on using ROS 2 (Humble) with [Rerun](https://github.com/rerun-io/rerun) and it would be super useful if it was possible to run it with other targets than linux-64.

**Comment by traversaro** [comment]
Hello @nikolausWest, see https://github.com/RoboStack/ros-humble/blob/main/CONTRIBUTING.md for how to add packages to architectures in which they are not available. Once a PR is ready, the CI will check if the package build fine or if there are problems, thanks!

**Comment by traversaro** [comment]
(And congrats on rerun, it seems quite cool!)
