### ISSUE TITLE
[Beginner Walkthrough] some questions about learning ROS2 on conda-ros-humble with ROS2 official Tutorials 

### ISSUE THREAD

**Issue by songyuc** [RoboStack/ros-humble#66]
Hi, guys!
I am a beginner at ROS2, and I plan to walk through the ROS2 official Tutorials with conda-ros-humble.
I hope to list my questions here and also write my tutorial blog for my teammates in the club of robots based on conda-ros-humble.
I don't know whether this is a good way to discuss it here.

Sincerely look forward to your guidance.

**Comment by Tobias-Fischer** [comment]
Yes, here is a good place. It would be good to open separate GitHub issues for the problems you might encounter. Out of interest, which robotics club is it?

**Comment by Tobias-Fischer** [comment]
As discussed, please open separate issues as they arise.

**Comment by songyuc** [comment]
Hi, guys!
The tutorial says: "As always, don’t forget to source ROS 2 in [every new terminal you open](https://docs.ros.org/en/humble/Tutorials/Beginner-CLI-Tools/Configuring-ROS2-Environment.html)."
According to my experience, the `conda activate ros_env` has contained the sourcing operation, am I right?

**Comment by Tobias-Fischer** [comment]
Yes
