### ISSUE TITLE
Package request: robot_localization upgrade

### ISSUE THREAD

**Issue by b1n-ch1kn** [RoboStack/ros-humble#71]
### Package name

robot_localization

### Operating System(s)

- [X] linux-64
- [ ] linux-aarch64
- [ ] osx-64
- [ ] osx-arm64
- [ ] win-64

### Additional context (optional)

Hi, I'm wondering if there's a way to upgrade individual packages? There is a bug in the current version (3.3.1) of `robot_localization` which is fixed in the newest version.
I know there's `--trigger_new_versions` with vinca so I tried building them locally (over 100 out of date packages), and while `robot_localization` built fine, there were a few others that failed when patching.
I can try to fix these but I've not worked with cmake patches before. Is it possible that newer versions of the failing packages don't require the patch anymore? 
Any pointers would be helpful as I'm sure it would be worth upgrading a number of packages :)

### Links and references (optional)

https://github.com/cra-ros-pkg/robot_localization

**Comment by Tobias-Fischer** [comment]
Locally you could simply delete the recipes that you do not want to build from the recipes folder

**Comment by b1n-ch1kn** [comment]
Sounds good, that worked for me. I also needed to change the build number from 3 to 4
Shall I open a PR with just the handfull of packages?

**Comment by wolfv** [comment]
Yes please @b1n-ch1kn
