### ISSUE TITLE
Fix linux-aarch64 CI issues

### ISSUE THREAD

**Issue by Tobias-Fischer** [RoboStack/ros-humble#8]
For some reason they time out after 25 minutes.

**Comment by Tobias-Fischer** [comment]
@wolfv - fixing this would be nice for the hackathon, especially if we are aiming to use more cirun.io

**Comment by wolfv** [comment]
This is for the CI that does not run on `cirun`, right?

**Comment by Tobias-Fischer** [comment]
Yes

**Comment by wolfv** [comment]
Hmm, both in the PR and the latest `aarch64` builds look "fine" to me (e.g. not timing out).

**Comment by Tobias-Fischer** [comment]
Awesome, might have fixed itself :)
