### ISSUE TITLE
Package request: vision_msgs_rviz_plugins

### ISSUE THREAD

**Issue by anand-bala** [RoboStack/ros-humble#83]
### Package name

vision_msgs_rviz_plugins

### Operating System(s)

- [X] linux-64
- [ ] linux-aarch64
- [ ] osx-64
- [ ] osx-arm64
- [ ] win-64

### Additional context (optional)

I tend to use the `vision_msgs` package quite frequently in my research, and wanted the RViz plugins to help with visualization (as opposed to boxes drawn by some node I created with a ton of bugs). I saw that the `vision_msgs` package isn't available for platforms other than `linux-64`, and was wondering if someone knows if there are any build issues with these packages I should be aware of.

If there are none, I can try submitting a PR for both `vision_msgs` and `vision_msgs_rviz_plugins` for `linux-64`.

**Comment by Tobias-Fischer** [comment]
It would be nice if you could open a pull request adding these two packages all platforms. There should be no build issues
