### ISSUE TITLE
Rebuild Windows against qt-main 5.15

### ISSUE THREAD

**Issue by Tobias-Fischer** [RoboStack/ros-humble#9]
Something goes wrong in either `python_qt_bindings` or `qt_gui_cpp` (or both). @traversaro offered to look into it.

**Comment by Tobias-Fischer** [comment]
Hiya @traversaro - did you have a chance to look into this?

**Comment by traversaro** [comment]
Sorry, I completly forgot about this. I will look into this in the next days.

**Comment by Tobias-Fischer** [comment]
This does not seem to be a problem anymore. At the moment, upstream just prints an error message that Windows is not yet supported (for qt-gui-cpp) and python_qt_binding seems to build fine. Closing here, will open another ticket if there are particular errors.
